In [2]:
import numpy as np

In [3]:
a1 = np.array([
    [1,2,3],
    [4,5,6]
])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a2 = np.array([
    [5,7,3],
    [9,0,1]
])
a2

array([[5, 7, 3],
       [9, 0, 1]])

In [5]:
np.concatenate([a1, a2], )

array([[1, 2, 3],
       [4, 5, 6],
       [5, 7, 3],
       [9, 0, 1]])

In [6]:
np.concatenate([a1, a2], axis=1)

array([[1, 2, 3, 5, 7, 3],
       [4, 5, 6, 9, 0, 1]])

In [9]:
x1 = np.random.randint(1,13, (3,4))
x1

array([[12,  7, 12,  7],
       [ 2,  2,  7,  3],
       [ 1, 12,  4,  1]])

In [10]:
x2 = np.arange(11,23).reshape(4,3)
x2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [14]:
x3 = np.arange(21, 37).reshape(4,4)
x3

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [16]:
np.concatenate([x1, x3], axis=0)

array([[12,  7, 12,  7],
       [ 2,  2,  7,  3],
       [ 1, 12,  4,  1],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

## OR

In [19]:
np.vstack([x1, x3])

array([[12,  7, 12,  7],
       [ 2,  2,  7,  3],
       [ 1, 12,  4,  1],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

## Horizontal Concatenation
combine arrays horizontally

In [18]:
np.concatenate([x2, x3], axis=1)

array([[11, 12, 13, 21, 22, 23, 24],
       [14, 15, 16, 25, 26, 27, 28],
       [17, 18, 19, 29, 30, 31, 32],
       [20, 21, 22, 33, 34, 35, 36]])

#### OR

In [20]:
np.hstack([x2, x3])

array([[11, 12, 13, 21, 22, 23, 24],
       [14, 15, 16, 25, 26, 27, 28],
       [17, 18, 19, 29, 30, 31, 32],
       [20, 21, 22, 33, 34, 35, 36]])

# Splitting of arrays
The opposite of concatenation is splitting, which is implemented by the functions
np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices
giving the split points:

In [23]:
x = [1, 2, 3, 99, 99, 3, 2, 1, 6,7]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1 6 7]


In [25]:
x = [2,4,5,6,8,9,11,4,5,10,12,15,16,18]


In [26]:
x1, x2, x3, x4 = np.split(x, [3, 7, 9])
print(x1, x2, x3, x4)

[2 4 5] [ 6  8  9 11] [4 5] [10 12 15 16 18]


### 2D array Split
split(array, indexes, axis=)
axis = 0 ====> vsplit
axis = 1 ====> hsplit

In [27]:
a = np.arange(16).reshape((4, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
x,y = np.split(a, 2)
print(x)
print('..............')
print(y)

[[0 1 2 3]
 [4 5 6 7]]
..............
[[ 8  9 10 11]
 [12 13 14 15]]


In [51]:
x,y = np.split(a, 2,axis=1)
print(x)
print('..............')
print(y)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
..............
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


###### np.vsplit used tp split array vertically 
syntax====> np.vsplit(array, [index1, index2, ...indexn])

In [32]:
upper, lower = np.vsplit(a, [1])
print(upper)
print('..................')
print(lower)

[[0 1 2 3]]
..................
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [46]:
upper,middle, lower = np.vsplit(a, [1,3])
print(upper)
print('..................')

print(middle)
print('..................')
print(lower)

[[0 1 2 3]]
..................
[[ 4  5  6  7]
 [ 8  9 10 11]]
..................
[[12 13 14 15]]


In [38]:
x =  np.vsplit(a, [1])
x

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [47]:
left, right = np.hsplit(a, [2])
print(left)
print('.........................')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
.........................
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [48]:
left,middle, right = np.hsplit(a, [2,3])
print(left)
print('.........................')
print(middle)
print('.........................')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
.........................
[[ 2]
 [ 6]
 [10]
 [14]]
.........................
[[ 3]
 [ 7]
 [11]
 [15]]
