# Numpy

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


DEPRECATION: Loading egg at c:\programdata\anaconda3\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330


In [8]:
import numpy as np

In [10]:
np.__version__

'1.26.4'

# Creating Arrays 

## 1- From Python List

In [12]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [13]:
type(a1)

numpy.ndarray

In [14]:
a2 =  np.array([1, 2, 3, 4], dtype='float32')
print(a2)
type(a2)

[1. 2. 3. 4.]


numpy.ndarray

## 2- Zeros Array

In [15]:
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [20]:
zero1 = np.zeros((3,4))
zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
zero1.ndim

2

## 3- Ones Array

In [17]:
one = np.ones(6)
one

array([1., 1., 1., 1., 1., 1.])

In [19]:
one1 = np.ones((3,5), dtype=int)
one1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 4- Array with Same Value

In [25]:
a3 = np.full(5,6)
print(a3)
a3.ndim

[6 6 6 6 6]


1

In [26]:
a4 = np.full((3,3), 100)
a4

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

## 5- Identity Array

In [29]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 6- Array from arange method

In [36]:
a5 = np.arange(3, 31,3)
a5

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [38]:
a5 = np.arange(3, 31,3).reshape(5,2)
a5

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24],
       [27, 30]])

## 7- Array from linspace Method
Create an array of five values evenly spaced between two numbers

In [39]:
a7 = np.linspace(0, 100, 5)
a7

array([  0.,  25.,  50.,  75., 100.])

In [45]:
a7 = np.linspace(1, 200, 10).reshape(5,2)
a7

array([[  1.        ,  23.11111111],
       [ 45.22222222,  67.33333333],
       [ 89.44444444, 111.55555556],
       [133.66666667, 155.77777778],
       [177.88888889, 200.        ]])

## 8- Array from random Method
Create a 3x3 array of uniformly distributed
 random values between 0 and 1

In [52]:
a8 = np.random.random(4)
a8

array([0.47847845, 0.49779936, 0.26191938, 0.15594952])

In [47]:
a8 = np.random.random((3,4))
a8

array([[0.56760727, 0.37000418, 0.35678021, 0.63456797],
       [0.15585767, 0.12617198, 0.28683852, 0.05755034],
       [0.92613558, 0.52646583, 0.1749206 , 0.70498699]])

## 9- Array from normal Method
Create a 3x3 array of normally distributed random values
 with mean 0 and standard deviation 1

In [58]:
a9 = np.random.normal(0,1,5)
a9

array([-0.58693241,  0.72958087,  1.33374617, -0.05677337, -0.25336372])

In [53]:
a9 = np.random.normal(0,1,(3,3))
a9

array([[ 0.54220591,  0.02391158, -0.63251856],
       [-0.88977878,  1.87480263,  0.94748866],
       [-1.20329905,  0.39152059, -0.41389402]])

In [55]:
a9.std()

0.9205020583268022

## 10- Array of Random Integer
 Create a 3x3 array of random integers in the interval [0, 10)

In [61]:
a10 = np.random.randint(0,10,4)
a10

array([0, 3, 0, 3])

In [62]:
a10 = np.random.randint(10,100,(3,3))
a10

array([[99, 52, 89],
       [38, 14, 32],
       [55, 81, 96]])

In [63]:
a11 = np.empty(3)
a11

array([1., 1., 1.])