In [2]:
import numpy as np

In [3]:
x1 = np.array([4,2,9,6,4,7,0,1])
x1

array([4, 2, 9, 6, 4, 7, 0, 1])

In [4]:
x1[5]

7

In [5]:
x1[-2]

0

In [6]:
x2 = np.random.randint(0,10,(3,4))
x2

array([[3, 2, 9, 2],
       [4, 6, 7, 6],
       [7, 5, 1, 9]])

In [30]:
x2[2:0:-1, 3:0:-2]

array([[9, 5],
       [6, 6]])

In [28]:
x2[-1:-3:-1, -1:-4:-2]

array([[9, 5],
       [6, 6]])

In [24]:
np.array([[9,5],[6,6]])

array([[9, 5],
       [6, 6]])

In [14]:
x2[2]
print('.....................')
print(x2[1,1])
print('.....................')
print(x2[2,3])
print('.....................')
print(x2[-1,-1])

.....................
6
.....................
9
.....................
9


In [15]:
x2[1, 1:3]

array([6, 7])

In [23]:
x2[0:2,0:2]

array([[3, 2],
       [4, 6]])

In [21]:
x2[0:2, -2:]

array([[9, 2],
       [7, 6]])

In [22]:
x2[0:3:2, 1:4:2]

array([[2, 2],
       [5, 9]])

## Subarrays as no-copy views

In [34]:
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
z=x[4: :-3, 3:0:-2]
z

array([[ 19,  17],
       [  4, 200]])

In [43]:
z[1,1] = 200
z

array([[ 19,  17],
       [  4, 200]])

In [44]:
x

array([[  1, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [38]:
z

array([[19, 17],
       [ 4,  2]])

In [40]:
z

array([[ 19,  17],
       [  4, 200]])

In [41]:
x

array([[  1, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [46]:
y = x[1:3, 2:4].copy()
y

array([[ 8,  9],
       [13, 14]])

In [50]:
y[0,1]=90
y

array([[ 8, 90],
       [13, 14]])

In [51]:
x

array([[  1, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

## Concatenation of arrays

In [52]:
x = np.arange(3)
y = np.arange(5,10)
print(x)
print(y)

[0 1 2]
[5 6 7 8 9]


In [54]:
np.concatenate([x,y])

array([0, 1, 2, 5, 6, 7, 8, 9])

In [55]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [56]:
np.concatenate([x,x])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [57]:
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.concatenate([x,y])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [59]:
np.concatenate([y,x])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2