# Array arithmetic

In [1]:
import numpy as np

In [2]:
x = np.arange(4)
print('x =', x)


x = [0 1 2 3]


In [3]:
print('x +5 = ', x+5)
print('x-5 = ', x-5)
print('x*5 = ', x*5)
print('x/5 = ', x/5)

x +5 =  [5 6 7 8]
x-5 =  [-5 -4 -3 -2]
x*5 =  [ 0  5 10 15]
x/5 =  [0.  0.2 0.4 0.6]


### OR Using Functions
All of these arithmetic operations are simply convenient wrappers around specific
functions built into NumPy; for example, the + operator is a wrapper for the add
function:

In [6]:
print('x +5 = ', np.add(x,5))
print('x-5 = ', np.subtract(x,5))
print('x*5 = ', np.multiply(x, 5))
print('x/5 = ', np.divide(x, 5))
print('x**5 = ', np.power(x, 5))
print('x/5 = ', np.mod(x, 5))

x +5 =  [5 6 7 8]
x-5 =  [-5 -4 -3 -2]
x*5 =  [ 0  5 10 15]
x/5 =  [0.  0.2 0.4 0.6]
x**5 =  [  0   1  32 243]
x/5 =  [0 1 2 3]


## Absolute value
Just as NumPy understands Python’s built-in arithmetic operators, it also understands
Python’s built-in absolute value function:n:

In [7]:
x = np.array([-2,-4, -1,0,1,-6])
print(x)
print('absolute x = ', abs(x))

[-2 -4 -1  0  1 -6]
absolute x =  [2 4 1 0 1 6]


The corresponding NumPy ufunc is np.absolute, which is also available under the
alias np.abs:

print('absolute x =', np.absolute(x))

 OR

In [9]:
print('absolute x =', np.abs(x))

absolute x = [2 4 1 0 1 6]


###### This ufunc can also handle complex data, in which the absolute value returns the 
magnitude:

In [10]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

# Trigonometric functions

In [12]:
theta = np.array([0, 30,45,60,90,180])
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [  0  30  45  60  90 180]
sin(theta) =  [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666 -0.80115264]
cos(theta) =  [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362 -0.59846007]
tan(theta) =  [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  1.33869021]


# Aggregations:

In [13]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [14]:
a1 = np.arange(11, 23).reshape(3,4)
a1

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

#### sum(array)----- sum of all elements in array

In [15]:
print('the sum of array',a )
np.sum(a)

the sum of array [1 2 3 4 5]


15

In [16]:
print('the sum of array', np.sum(a1) )

the sum of array 198


### sum(array, axis)
#### axis=1 means row wise sum


In [17]:
print('the sum of array', np.sum(a1, axis=1) )

the sum of array [50 66 82]


#### axis=0 means column wise sum

In [18]:
print('the sum of array', np.sum(a1, axis=0) )

the sum of array [45 48 51 54]


### min(array)
====> return minimum value from array

In [19]:
np.min(a1)

11

##### min(array, axis)
axis=0 means column wise
axis=1 means row wise

In [22]:
print('row wise minimum', np.min(a1, axis=1))

row wise minimum [11 15 19]


In [23]:
print('column wise minimum', np.min(a1, axis=0))

column wise minimum [11 12 13 14]


### max(array)
return maximum value from array

In [20]:
np.max(a1)

22

## Similarly all aggregate functions work

In [32]:
print('Min: ', np.min(a1))
print('Max: ', np.max(a1))
print('Mean: ', np.mean(a1))
print('Standard deviation: ', np.std(a1))
print('Variance: ', np.var(a1))
print('Median: ', np.median(a1))
print('Product: ', np.prod(a1))
print('Percentile: ', np.percentile(a1,2))

Min:  11
Max:  22
Mean:  16.5
Standard deviation:  3.452052529534663
Variance:  11.916666666666666
Median:  16.5
Product:  17180672
Percentile:  11.22


#### np.any(condition)
if condition satisfy for atleast 1 elemnet it return true

In [27]:
np.any(a1>13) # we have atleast 1 element in array a1 whose vale is greater than 13

True

### np.all(condition)
if all elements satisfy condition it return True else False

In [25]:
np.all(a1>13)# we have all element in array a1 whose vale is greater than 13

False

In [25]:
np.all(a1>13)# we have all element in array a1 whose vale is greater than 13

False

In [34]:
a2 = np.array([
    [2,3,np.NaN,5],
    [4,np.NaN, 2,1]
])
a2

array([[ 2.,  3., nan,  5.],
       [ 4., nan,  2.,  1.]])

In [36]:
np.nansum(a2)

17.0

In [37]:
print('Min: ', np.nanmin(a2))
print('Max: ', np.nanmax(a2))
print('Mean: ', np.nanmean(a1))
print('Standard deviation: ', np.nanstd(a1))
print('Variance: ', np.nanvar(a1))
print('Median: ', np.nanmedian(a1))
print('Product: ', np.nanprod(a1))
print('Percentile: ', np.nanpercentile(a1,2))

Min:  11
Max:  22
Mean:  16.5
Standard deviation:  3.452052529534663
Variance:  11.916666666666666
Median:  16.5
Product:  17180672
Percentile:  11.22
