# Computation on Arrays: Broadcasting

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([5,5,5])
print(a)
print(b)

[0 1 2]
[5 5 5]


In [3]:
a + b

array([5, 6, 7])

In [4]:
a + 5

array([5, 6, 7])

In [5]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
c = np.array([0,2,5]).reshape(3,1)
c

array([[0],
       [2],
       [5]])

In [8]:
M + c

array([[1., 1., 1.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [9]:
x = np.arange(1,4)
y = np.arange(4,7).reshape(3,1)
print(x)
print(y)

[1 2 3]
[[4]
 [5]
 [6]]


In [10]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [15]:
a = np.ones((3,3))
b = np.arange(3)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [16]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])