# Fancy Indexing

In [2]:
import numpy as np
a = np.arange(1,31).reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [9]:
a[2]

array([13, 14, 15, 16, 17, 18])

In [5]:
a[: ,1:4 :2]

array([[ 2,  4],
       [ 8, 10],
       [14, 16],
       [20, 22],
       [26, 28]])

In [8]:
a[0:4:3, : 5: 2 ]

array([[ 1,  3,  5],
       [19, 21, 23]])

## Fancy Indexing

In [10]:
a  = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
[a[2], a[-1], a[0]]

[7, 14, 5]

In [12]:
ind = [2,-1,0]
a[ind]

array([ 7, 14,  5])

In [13]:
a = np.arange(10, 35).reshape(5,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [17]:
# 25
# 10...
# 20...
[a[3], a[0], a[2]]

[array([25, 26, 27, 28, 29]),
 array([10, 11, 12, 13, 14]),
 array([20, 21, 22, 23, 24])]

In [ ]:
row = [3, 0, 2]
a[row]

In [22]:
a[  : , [3,0,4]]

array([[13, 10, 14],
       [18, 15, 19],
       [23, 20, 24],
       [28, 25, 29],
       [33, 30, 34]])

In [23]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [24]:
28,22,26,32,13
row = [3, 2, 3,-1, 0 ]
col = [3, 2, 1, 2, 3]
a[row, col]

array([28, 22, 26, 32, 13])

In [25]:
row = [0,1,2,3,4]
col = [4,3,2,1,0]
a[row, col]

array([14, 18, 22, 26, 30])

In [29]:
a[[1,1,2,2], [1,2,1,2]]

array([16, 17, 21, 22])

In [28]:
a[[1,1,2,2], [1,2,1,2]].reshape(2,2)

array([[16, 17],
       [21, 22]])

In [27]:
a[1:3, 1:3]

array([[16, 17],
       [21, 22]])

In [30]:
a[2,2] = 2

In [31]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21,  2, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [37]:
a = np.arange(11, 20)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
i = [1, 3, -3]
a[i] = 20
a

array([11, 20, 13, 20, 15, 16, 20, 18, 19])

In [40]:
i = [0,2,4]
a[i] = 10,30,50
a

array([10, 20, 30, 20, 50, 16, 20, 18, 19])

In [41]:
a = np.arange(10, 35).reshape(5,5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [43]:
row = [1]
col = [2,3]
a[row, col] = 60, 70
a

array([[10, 11, 12, 13, 14],
       [15, 16, 60, 70, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

##### OR

In [44]:
a[1, 2:4] = 60, 70 


In [45]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 60, 70, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])