# 

In [1]:
import numpy as np

In [2]:
x = np.array([2,1,4,3,5])
x

array([2, 1, 4, 3, 5])

To return a sorted version of the array without modifying the input, you can use np.sort(array)

In [3]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [4]:
x

array([2, 1, 4, 3, 5])

In [5]:
x.sort()

In [6]:
x

array([1, 2, 3, 4, 5])

In [13]:
a= np.random.randint(0, 10, (4, 6))
a

array([[3, 2, 4, 1, 8, 4],
       [5, 4, 4, 9, 1, 7],
       [1, 7, 2, 9, 4, 8],
       [5, 4, 3, 5, 5, 8]])

In [9]:
np.sort(a, axis=0)

array([[1, 1, 0, 0, 0, 1],
       [2, 6, 0, 5, 2, 2],
       [4, 7, 8, 7, 6, 8],
       [5, 8, 9, 7, 9, 9]])

In [10]:
np.sort(a, axis=1)

array([[0, 0, 5, 7, 7, 8],
       [1, 1, 2, 2, 5, 8],
       [0, 0, 1, 2, 6, 8],
       [4, 6, 7, 9, 9, 9]])

In [11]:
np.sort(a)

array([[0, 0, 5, 7, 7, 8],
       [1, 1, 2, 2, 5, 8],
       [0, 0, 1, 2, 6, 8],
       [4, 6, 7, 9, 9, 9]])

In [12]:
a.sort()
a

array([[0, 0, 5, 7, 7, 8],
       [1, 1, 2, 2, 5, 8],
       [0, 0, 1, 2, 6, 8],
       [4, 6, 7, 9, 9, 9]])

In [14]:
a

array([[3, 2, 4, 1, 8, 4],
       [5, 4, 4, 9, 1, 7],
       [1, 7, 2, 9, 4, 8],
       [5, 4, 3, 5, 5, 8]])

In [15]:
np.partition(a, 5)

array([[1, 3, 2, 4, 4, 8],
       [1, 4, 4, 5, 7, 9],
       [1, 2, 4, 7, 8, 9],
       [5, 3, 4, 5, 5, 8]])

In [20]:
np.partition(a, 4, axis=1)

array([[1, 3, 2, 4, 4, 8],
       [1, 4, 4, 5, 7, 9],
       [1, 2, 4, 7, 8, 9],
       [5, 3, 4, 5, 5, 8]])

In [21]:
a.shape

(4, 6)